WORDS = {
    "Easy": ["APPLE","HOUSE","TABLE","MUSIC","TIGER"],
    "Medium": ["PYTHON","LAPTOP","SCIENCE","NETWORK","GAMING"],
    "Hard": ["PROGRAMMING","CYBERSECURITY","DEVELOPMENT","INTELLIGENCE","ARTIFICIAL"]
}